model {
  model_wrapper_class: 'FasterRCNNWrapper'
  model_path: 'PATH_TO_BE_CONFIGURED.pb'
  labels_path: 'PATH_TO_BE_CONFIGURED.txt'
}
source_dir: 'PATH_TO_BE_CONFIGURED'
test_dir: 'PATH_TO_BE_CONFIGURED'
resize_images: false
resize_patches: false
target_class: 'pedestrian'
bottlenecks: 'block4_unit_1'
max_imgs: 1000
slic {
  n_segments: [5, 10, 15]
}
