model {
  model_wrapper_class: 'InceptionV3Wrapper'
  model_path: 'PATH_TO_BE_CONFIGURED.pb'
  labels_path: 'PATH_TO_BE_CONFIGURED.txt'
}
source_dir: 'PATH_TO_BE_CONFIGURED'
test_dir: 'PATH_TO_BE_CONFIGURED'
resize_images: true
resize_patches: true
target_class: 'zebra'
bottlenecks: 'Mixed_7a'
max_imgs: 40
slic {
  n_segments: [15, 50, 80]
}
